In [ ]:
import pandas as pd

In [ ]:
df1 = pd.read_csv('/content/dataset.csv')

In [ ]:
df1.head()

                                              review  rating
0            Всё норм. Мужу понравилось, как всегда.       5
1                      Все пришло попробовал отлично       5
2  Супер! Оригинал, выгодней намного чем в магази...       5
3  Шикарные лезвия, 4 штуки в упаковке (фоткала у...       5
4  На первый взгляд очень даже хорошие кассеты. П...       5

In [ ]:
df1.rename(columns = {"review" : "text", "rating" : "label"}, inplace = True)

In [ ]:
df1

                                                    text  label
0                Всё норм. Мужу понравилось, как всегда.      5
1                          Все пришло попробовал отлично      5
2      Супер! Оригинал, выгодней намного чем в магази...      5
3      Шикарные лезвия, 4 штуки в упаковке (фоткала у...      5
4      На первый взгляд очень даже хорошие кассеты. П...      5
...                                                  ...    ...
70078                         Для тренировок в сммый раз      5
70079                                      Хорошая майка      5
70080        Майка не понравилась-очень тонкий материал!      3
70081  На рост 190 см Вес 94 кг .подошел отлично разм...      5
70082  Материал очень приятный , качество хорошее , м...      5

[70083 rows x 2 columns]

In [ ]:
df1.loc[(df1.label <=3 ), 'label'] = 'negative'
df1.loc[(df1.label == 4), 'label'] = 'neutral'
df1.loc[(df1.label == 5), 'label'] = 'positive'

In [ ]:
df1

                                                    text     label
0                Всё норм. Мужу понравилось, как всегда.  positive
1                          Все пришло попробовал отлично  positive
2      Супер! Оригинал, выгодней намного чем в магази...  positive
3      Шикарные лезвия, 4 штуки в упаковке (фоткала у...  positive
4      На первый взгляд очень даже хорошие кассеты. П...  positive
...                                                  ...       ...
70078                         Для тренировок в сммый раз  positive
70079                                      Хорошая майка  positive
70080        Майка не понравилась-очень тонкий материал!  negative
70081  На рост 190 см Вес 94 кг .подошел отлично разм...  positive
70082  Материал очень приятный , качество хорошее , м...  positive

[70083 rows x 2 columns]

In [ ]:
df1.label = df1.label.astype('str')
df1.label.dtypes

dtype('O')

In [ ]:
df1.head()

                                                text     label
0            Всё норм. Мужу понравилось, как всегда.  positive
1                      Все пришло попробовал отлично  positive
2  Супер! Оригинал, выгодней намного чем в магази...  positive
3  Шикарные лезвия, 4 штуки в упаковке (фоткала у...  positive
4  На первый взгляд очень даже хорошие кассеты. П...  positive

In [ ]:
df1.dtypes

text     object
label    object
dtype: object

In [ ]:
df1.to_csv('wildberries.csv', index = True, index_label = "id")

In [ ]:
df2 = pd.read_excel('/content/Test_data_marked.xlsx')

In [ ]:
df2

,Общая оценка,Цена/качество,Расположение,Качество сна,Номера,Чистота,Обслуживание,Текст отзыва
0,5.0,5.0,5.0,NaN,5.0,5.0,5.0,Элегантный отель в самом центре Дубай. Красивы...
1,5.0,5.0,5.0,5.0,5.0,5.0,5.0,Если стиль вашей поездки в Дубай-- это шоппинг...
2,5.0,5.0,5.0,5.0,5.0,5.0,5.0,Провели с супругой там уик енд. Брали самый лю...
3,5.0,4.0,5.0,5.0,5.0,5.0,5.0,"По дороге домой для того, чтобы перекантоватьс..."
4,4.0,3.0,2.0,4.0,4.0,4.0,4.0,"меня впечатлили размеры! самый огромный номер,..."
...,...,...,...,...,...,...,...,...
6871,5.0,4.0,4.0,5.0,5.0,4.0,5.0,"Для нас было плюсом, что в этом отеле можно ос..."
6872,5.0,5.0,4.0,5.0,5.0,5.0,5.0,Очень понравился отель.Хорошие номера с кухней...
6873,5.0,5.0,4.0,5.0,5.0,5.0,4.0,"В Петербурге бываю очень часто, поэтому появле..."
6874,5.0,5.0,5.0,5.0,5.0,5.0,5.0,Изумительное место! Я просто не ожидала такого...
6875,4.0,4.0,5.0,5.0,5.0,5.0,5.0,"Останавливались в этом отеле в августе 2013, р..."

In [ ]:
df3 = pd.read_excel('/content/Training_data_marked.xlsx')

In [ ]:
df3.head()

,Unnamed: 0,Цена/качество,Расположение,Качество сна,Номера,Чистота,Обслуживание,Unnamed: 7
0,4,4.0,4.0,5.0,4.0,4.0,5.0,"Очень достойный отель с прекрасными номерами, ..."
1,4,NaN,3.0,NaN,NaN,4.0,4.0,"Остановились в Барселоне проездом, т.к. нужно ..."
2,4,3.0,3.0,5.0,5.0,3.0,4.0,Типичная сетевая гостиница. Главный плюс-шикар...
3,1,NaN,NaN,NaN,2.0,1.0,1.0,"Начнем с того, что в этом отеле не берут деньг..."
4,5,NaN,NaN,NaN,NaN,NaN,NaN,"Отель находится в отдалении от центра,но пешко..."

In [ ]:
df3 = df3.rename(columns = {"Unnamed: 0":"Общая оценка", "Unnamed: 7":"Текст отзыва"})

In [ ]:
df = pd.concat([df3, df2], ignore_index=True)

In [ ]:
df

,Общая оценка,Цена/качество,Расположение,Качество сна,Номера,Чистота,Обслуживание,Текст отзыва
0,4.0,4.0,4.0,5.0,4.0,4.0,5.0,"Очень достойный отель с прекрасными номерами, ..."
1,4.0,NaN,3.0,NaN,NaN,4.0,4.0,"Остановились в Барселоне проездом, т.к. нужно ..."
2,4.0,3.0,3.0,5.0,5.0,3.0,4.0,Типичная сетевая гостиница. Главный плюс-шикар...
3,1.0,NaN,NaN,NaN,2.0,1.0,1.0,"Начнем с того, что в этом отеле не берут деньг..."
4,5.0,NaN,NaN,NaN,NaN,NaN,NaN,"Отель находится в отдалении от центра,но пешко..."
...,...,...,...,...,...,...,...,...
56773,5.0,4.0,4.0,5.0,5.0,4.0,5.0,"Для нас было плюсом, что в этом отеле можно ос..."
56774,5.0,5.0,4.0,5.0,5.0,5.0,5.0,Очень понравился отель.Хорошие номера с кухней...
56775,5.0,5.0,4.0,5.0,5.0,5.0,4.0,"В Петербурге бываю очень часто, поэтому появле..."
56776,5.0,5.0,5.0,5.0,5.0,5.0,5.0,Изумительное место! Я просто не ожидала такого...
56777,4.0,4.0,5.0,5.0,5.0,5.0,5.0,"Останавливались в этом отеле в августе 2013, р..."

In [ ]:
df_new = df[["Текст отзыва", "Общая оценка"]]

In [ ]:
df_new.rename(columns ={"Текст отзыва":"text","Общая оценка":"label"}, inplace = True)

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:5047: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

In [ ]:
df_new

                                                    text  label
0      Очень достойный отель с прекрасными номерами, ...    4.0
1      Остановились в Барселоне проездом, т.к. нужно ...    4.0
2      Типичная сетевая гостиница. Главный плюс-шикар...    4.0
3      Начнем с того, что в этом отеле не берут деньг...    1.0
4      Отель находится в отдалении от центра,но пешко...    5.0
...                                                  ...    ...
56773  Для нас было плюсом, что в этом отеле можно ос...    5.0
56774  Очень понравился отель.Хорошие номера с кухней...    5.0
56775  В Петербурге бываю очень часто, поэтому появле...    5.0
56776  Изумительное место! Я просто не ожидала такого...    5.0
56777  Останавливались в этом отеле в августе 2013, р...    4.0

[56778 rows x 2 columns]

In [ ]:
df_new.label.dtype()

TypeError: ignored

In [ ]:
df_new.loc[(df_new.label <=3 ), 'label'] = 'negative'
df_new.loc[(df_new.label == 4), 'label'] = 'neutral'
df_new.loc[(df_new.label == 5), 'label'] = 'positive'

/usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py:1817: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)

In [ ]:
df_new

                                                    text     label
0      Очень достойный отель с прекрасными номерами, ...   neutral
1      Остановились в Барселоне проездом, т.к. нужно ...   neutral
2      Типичная сетевая гостиница. Главный плюс-шикар...   neutral
3      Начнем с того, что в этом отеле не берут деньг...  negative
4      Отель находится в отдалении от центра,но пешко...  positive
...                                                  ...       ...
56773  Для нас было плюсом, что в этом отеле можно ос...  positive
56774  Очень понравился отель.Хорошие номера с кухней...  positive
56775  В Петербурге бываю очень часто, поэтому появле...  positive
56776  Изумительное место! Я просто не ожидала такого...  positive
56777  Останавливались в этом отеле в августе 2013, р...   neutral

[56778 rows x 2 columns]

In [ ]:
df_new.to_csv('hotel.csv', index = True, index_label = 'id')

In [ ]:
df_drna = df.dropna()
df_drna = df_drna.reset_index(drop=True)

In [ ]:
df_drna.head()

,Общая оценка,Цена/качество,Расположение,Качество сна,Номера,Чистота,Обслуживание,Текст отзыва
0,4.0,4.0,4.0,5.0,4.0,4.0,5.0,"Очень достойный отель с прекрасными номерами, ..."
1,4.0,3.0,3.0,5.0,5.0,3.0,4.0,Типичная сетевая гостиница. Главный плюс-шикар...
2,5.0,4.0,4.0,5.0,5.0,5.0,5.0,В сети отелей NH Collection отдыхаем впервые. ...
3,5.0,5.0,4.0,5.0,5.0,5.0,5.0,"У отеля неплохое расположение, рядом есть разл..."
4,4.0,4.0,3.0,5.0,5.0,5.0,5.0,"Хороший отель, номера чистые, сервис на уровне..."

In [ ]:
df_drna['Общая оценка']

0        4.0
1        4.0
2        5.0
3        5.0
4        4.0
        ...
15717    5.0
15718    5.0
15719    5.0
15720    5.0
15721    4.0
Name: Общая оценка, Length: 15722, dtype: float64

In [ ]:
dff = df_drna[df_drna['Общая оценка'] <=3]
dff.drop("Общая оценка", axis=1, inplace=True)
dff = dff.reset_index(drop=True)

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4913: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

In [ ]:
dff.drop("Общая оценка", axis=1, inplace=True)

KeyError: ignored

In [ ]:
dff[dff[["Цена/качество",	"Расположение",	"Качество сна",	"Номера",	"Чистота",	"Обслуживание"]]<=3]

,Цена/качество,Расположение,Качество сна,Номера,Чистота,Обслуживание,Текст отзыва
0,3.0,NaN,NaN,3.0,NaN,NaN,NaN
1,3.0,3.0,NaN,NaN,NaN,NaN,NaN
2,3.0,NaN,2.0,2.0,3.0,2.0,NaN
3,NaN,NaN,NaN,3.0,NaN,NaN,NaN
4,2.0,NaN,NaN,3.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...
2346,1.0,1.0,1.0,1.0,3.0,1.0,NaN
2347,1.0,NaN,3.0,3.0,3.0,NaN,NaN
2348,3.0,3.0,NaN,NaN,NaN,3.0,NaN
2349,1.0,NaN,3.0,3.0,1.0,2.0,NaN
2350,1.0,1.0,NaN,1.0,1.0,1.0,NaN

In [ ]:
dff.apply(lambda row: row[row <=3].index, axis=1)

TypeError: ignored

In [ ]:
dff["Цена/качество"]

0       3.0
1       3.0
2       3.0
3       5.0
4       2.0
       ...
2346    1.0
2347    1.0
2348    3.0
2349    1.0
2350    1.0
Name: Цена/качество, Length: 2351, dtype: float64

In [ ]:
df['Причина'] =

SyntaxError: ignored

In [ ]:
dff.info()

In [ ]:
dff

In [ ]:
data = pd.read_csv('/content/data1.csv', error_bad_lines=False, engine="python", nrows=100000)

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:3326: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version.


  exec(code_obj, self.user_global_ns, self.user_ns)

In [ ]:
import csv

In [ ]:
import pandas as pd

In [ ]:
data1 = pd.read_csv('/content/data1.csv', encoding='utf-16 BE', header=0)

In [ ]:
data1.head()

In [ ]:
data2 = pd.read_csv('/content/data1.csv', error_bad_lines=False, engine="python", skiprows=200000,nrows=300000)

Error: ignored

In [ ]:
data3 = pd.read_csv('/content/data1.csv', error_bad_lines=False, engine="python",skiprows=300000, nrows=400000)

UnicodeDecodeError: ignored

In [ ]:
data4 = pd.read_csv('/content/data1.csv', error_bad_lines=False, engine="python", skiprows=400000)

UnicodeDecodeError: ignored

In [ ]:
data

                                                  Review  Rating
0      3D Touch просто восхитительная вещь! Заряд дер...       5
1      Отключается при температуре близкой к нулю, не...       4
2      В Apple окончательно решили не заморачиваться,...       3
3      Постарался наиболее ёмко и коротко описать все...       4
4      Достойный телефон. Пользоваться одно удовольст...       5
...                                                  ...     ...
99995  Не покупайте это Г. Ксениум уже не тот. Буду в...       3
99996  Хотелось иметь простую звонилку, но с выходом ...       4
99997  Купил 04.08 за 1.6кр доволен как слон))\rРазби...       4
99998  К сожалению производители телефонов, не только...       1
99999                    Отстой, больше Philips не куплю       2

[100000 rows x 2 columns]

In [ ]:
d = pd.read_csv("/content/cleaned_kaspi_reviews.csv", error_bad_lines=False, engine="python").drop(['index0', 'index1'], axis='columns')

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:3326: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version.


  exec(code_obj, self.user_global_ns, self.user_ns)

In [ ]:
d

,language,rating,category,combined_text
0,russian,5.0,perfumes,"парфюм оригинальный . все , профессиональный ..."
1,russian,5.0,perfumes,любимый dkny . запах просто шикарный . спасибо...
2,russian,5.0,perfumes,шикарный запах ! безумно нравиться ! не пожале...
3,kazakh,5.0,perfumes,иісі қатты ұнады .
4,russian,4.0,perfumes,"запах просто классный , то , нужно летний вр..."
...,...,...,...,...
119043,russian,5.0,headphones,"звук высокий средний , немного токсичный высо..."
119044,russian,4.0,headphones,"вполне сносный наушник , но , думать , не с..."
119045,russian,5.0,headphones,наушник просто супер
119046,russian,4.0,headphones,все супер бас маловато
119047,russian,5.0,headphones,отличный звук . система шумоподавление . качес...

In [ ]:
d= d[['rating', 'combined_text']]

In [ ]:
d.rename(columns ={"rating": "label", "combined_text": "text"}, inplace = True)

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:5047: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

In [ ]:
d.loc[(d.label <=3 ), 'label'] = 'negative'
d.loc[(d.label == 4), 'label'] = 'neutral'
d.loc[(d.label == 5), 'label'] = 'positive'

/usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py:1817: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)

In [ ]:
d

           label                                               text
0       positive  парфюм оригинальный . все ,  профессиональный ...
1       positive  любимый dkny . запах просто шикарный . спасибо...
2       positive  шикарный запах ! безумно нравиться ! не пожале...
3       positive                                 иісі қатты ұнады .
4        neutral  запах просто классный ,  то ,  нужно летний вр...
...          ...                                                ...
119043  positive  звук высокий средний ,  немного токсичный высо...
119044   neutral  вполне сносный наушник ,  но ,  думать ,  не с...
119045  positive                               наушник просто супер
119046   neutral                             все супер бас маловато
119047  positive  отличный звук . система шумоподавление . качес...

[119048 rows x 2 columns]

In [ ]:
d.to_csv('rewiews.csv', index = True, index_label = 'id')

In [ ]:
data

In [ ]:
f = open('data2.txt','r')

In [ ]:
f

In [ ]:
print(f.read())

UnicodeDecodeError: ignored

In [ ]:
paragraphs = f.split(',5')

AttributeError: ignored

In [ ]:
dfff = pd.read_csv("/content/women-clothing-accessories.3-class.balanced.csv")

UnicodeDecodeError: ignored

In [ ]:
df = pd.read_csv("/content/women-clothing-accessories.3-class.balanced_utf.csv", error_bad_lines=False, engine="python")

Skipping line 10: ',' expected after '"'
Skipping line 25: ',' expected after '"'
Skipping line 81: ',' expected after '"'
Skipping line 111: ',' expected after '"'
Skipping line 124: ',' expected after '"'
Skipping line 140: ',' expected after '"'
Skipping line 208: ',' expected after '"'
Skipping line 211: ',' expected after '"'
Skipping line 248: ',' expected after '"'
Skipping line 254: ',' expected after '"'
Skipping line 309: ',' expected after '"'
Skipping line 341: ',' expected after '"'
Skipping line 359: ',' expected after '"'
Skipping line 425: ',' expected after '"'
Skipping line 503: ',' expected after '"'
Skipping line 537: ',' expected after '"'
Skipping line 574: ',' expected after '"'
Skipping line 676: ',' expected after '"'
Skipping line 680: ',' expected after '"'
Skipping line 695: ',' expected after '"'
Skipping line 715: ',' expected after '"'
Skipping line 729: ',' expected after '"'
Skipping line 766: ',' expected after '"'
Skipping line 778: ',' expected after '"'
Skipping line 817: ',' expected after '"'
Skipping line 820: ',' expected after '"'
Skipping line 847: ',' expected after '"'
Skipping line 920: ',' expected after '"'
Skipping line 923: ',' expected after '"'
Skipping line 928: ',' expected after '"'
Skipping line 974: ',' expected after '"'
Skipping line 978: ',' expected after '"'
Skipping line 1008: ',' expected after '"'
Skipping line 1058: ',' expected after '"'
Skipping line 1061: ',' expected after '"'
Skipping line 1076: ',' expected after '"'
Skipping line 1085: ',' expected after '"'
Skipping line 1094: ',' expected after '"'
Skipping line 1139: ',' expected after '"'
Skipping line 1156: ',' expected after '"'
Skipping line 1164: ',' expected after '"'
Skipping line 1178: ',' expected after '"'
Skipping line 1179: ',' expected after '"'
Skipping line 1248: ',' expected after '"'
Skipping line 1291: ',' expected after '"'
Skipping line 1313: ',' expected after '"'
Skipping line 1325: ',' expected after '"'
Skipping line 1334: ',' expected after '"'
Skipping line 1376: ',' expected after '"'
Skipping line 1377: ',' expected after '"'
Skipping line 1417: ',' expected after '"'
Skipping line 1418: ',' expected after '"'
Skipping line 1446: ',' expected after '"'
Skipping line 1492: ',' expected after '"'
Skipping line 1510: ',' expected after '"'
Skipping line 1517: ',' expected after '"'
Skipping line 1618: ',' expected after '"'
Skipping line 1629: ',' expected after '"'
Skipping line 1684: ',' expected after '"'
Skipping line 1731: ',' expected after '"'
Skipping line 1747: ',' expected after '"'
Skipping line 1758: ',' expected after '"'
Skipping line 1783: ',' expected after '"'
Skipping line 1788: ',' expected after '"'
Skipping line 1843: ',' expected after '"'
Skipping line 1844: ',' expected after '"'
Skipping line 1849: ',' expected after '"'
Skipping line 1899: ',' expected after '"'
Skipping line 1939: ',' expected after '"'
Skipping line 1943: ',' expected after '"'
Skipping line 1967: ',' expected after '"'
Skipping line 1970: ',' expected after '"'
Skipping line 2023: ',' expected after '"'
Skipping line 2044: ',' expected after '"'
Skipping line 2070: ',' expected after '"'
Skipping line 2083: ',' expected after '"'
Skipping line 2097: ',' expected after '"'
Skipping line 2110: ',' expected after '"'
Skipping line 2117: ',' expected after '"'
Skipping line 2124: ',' expected after '"'
Skipping line 2185: ',' expected after '"'
Skipping line 2214: ',' expected after '"'
Skipping line 2268: ',' expected after '"'
Skipping line 2272: ',' expected after '"'
Skipping line 2305: ',' expected after '"'
Skipping line 2313: ',' expected after '"'
Skipping line 2318: ',' expected after '"'
Skipping line 2327: ',' expected after '"'
Skipping line 2347: ',' expected after '"'
Skipping line 2367: ',' expected after '"'
Skipping line 2466: ',' expected after '"'
Skipping line 2501: ',' expected after '"'
Skipping line 2516: ',' expected after '"'
Skipping line 2554: ',' expected after '"'
Skipping line 2589: ',' expected after '"'
Skipping line 2623: ',' expected after '"'
Skipping line 2661: ',' expected after '"'
Skipping line 2664: ',' expected after '"'
Skipping line 2813: ',' expected after '"'
Skipping line 2827: ',' expected after '"'
Skipping line 2847: ',' expected after '"'
Skipping line 2855: ',' expected after '"'
Skipping line 2857: ',' expected after '"'
Skipping line 2893: ',' expected after '"'
Skipping line 2908: ',' expected after '"'
Skipping line 2926: ',' expected after '"'
Skipping line 2946: ',' expected after '"'
Skipping line 2955: ',' expected after '"'
Skipping line 3047: ',' expected after '"'
Skipping line 3100: ',' expected after '"'
Skipping line 3103: ',' expected after '"'
Skipping line 3217: ',' expected after '"'
Skipping line 3263: ',' expected after '"'
Skipping line 3268: ',' expected after '"'
Skipping line 3354: ',' expected after '"'
Skipping line 3366: ',' expected after '"'
Skipping line 3399: ',' expected after '"'
Skipping line 3410: ',' expected after '"'
Skipping line 3460: ',' expected after '"'
Skipping line 3478: ',' expected after '"'
Skipping line 3480: ',' expected after '"'
Skipping line 3482: ',' expected after '"'
Skipping line 3512: ',' expected after '"'
Skipping line 3546: ',' expected after '"'
Skipping line 3548: ',' expected after '"'
Skipping line 3569: ',' expected after '"'
Skipping line 3581: ',' expected after '"'
Skipping line 3586: ',' expected after '"'
Skipping line 3644: ',' expected after '"'
Skipping line 3704: ',' expected after '"'
Skipping line 3752: ',' expected after '"'
Skipping line 3779: ',' expected after '"'
Skipping line 3790: ',' expected after '"'
Skipping line 3825: ',' expected after '"'
Skipping line 3966: ',' expected after '"'
Skipping line 3973: ',' expected after '"'
Skipping line 4014: ',' expected after '"'
Skipping line 4049: ',' expected after '"'
Skipping line 4052: ',' expected after '"'
Skipping line 4136: ',' expected after '"'
Skipping line 4152: ',' expected after '"'
Skipping line 4170: ',' expected after '"'
Skipping line 4171: ',' expected after '"'
Skipping line 4173: ',' expected after '"'
Skipping line 4211: ',' expected after '"'
Skipping line 4224: ',' expected after '"'
Skipping line 4246: ',' expected after '"'
Skipping line 4248: ',' expected after '"'
Skipping line 4263: ',' expected after '"'
Skipping line 4266: ',' expected after '"'
Skipping line 4274: ',' expected after '"'
Skipping line 4335: ',' expected after '"'
Skipping line 4338: ',' expected after '"'
Skipping line 4352: ',' expected after '"'
Skipping line 4382: ',' expected after '"'
Skipping line 4396: ',' expected after '"'
Skipping line 4493: ',' expected after '"'
Skipping line 4585: ',' expected after '"'
Skipping line 4641: ',' expected after '"'
Skipping line 4698: ',' expected after '"'
Skipping line 4729: ',' expected after '"'
Skipping line 4735: ',' expected after '"'
Skipping line 4777: ',' expected after '"'
Skipping line 4779: ',' expected after '"'
Skipping line 4786: ',' expected after '"'
Skipping line 4832: ',' expected after '"'
Skipping line 4851: ',' expected after '"'
Skipping line 4882: ',' expected after '"'
Skipping line 4952: ',' expected after '"'
Skipping line 4953: ',' expected after '"'
Skipping line 4957: ',' expected after '"'
Skipping line 5025: ',' expected after '"'
Skipping line 5050: ',' expected after '"'
Skipping line 5111: ',' expected after '"'
Skipping line 5142: ',' expected after '"'
Skipping line 5156: ',' expected after '"'
Skipping line 5160: ',' expected after '"'
Skipping line 5174: ',' expected after '"'
Skipping line 5200: ',' expected after '"'
Skipping line 5225: ',' expected after '"'
Skipping line 5247: ',' expected after '"'
Skipping line 5305: ',' expected after '"'
Skipping line 5337: ',' expected after '"'
Skipping line 5379: ',' expected after '"'
Skipping line 5382: ',' expected after '"'
Skipping line 5385: ',' expected after '"'
Skipping line 5515: ',' expected after '"'
Skipping line 5516: ',' expected after '"'
Skipping line 5520: ',' expected after '"'
Skipping line 5557: ',' expected after '"'
Skipping line 5576: ',' expected after '"'
Skipping line 5641: ',' expected after '"'
Skipping line 5657: ',' expected after '"'
Skipping line 5670: ',' expected after '"'
Skipping line 5680: ',' expected after '"'
Skipping line 5781: ',' expected after '"'
Skipping line 5786: ',' expected after '"'
Skipping line 5832: ',' expected after '"'
Skipping line 5922: ',' expected after '"'
Skipping line 5961: ',' expected after '"'
Skipping line 5965: ',' expected after '"'
Skipping line 5985: ',' expected after '"'
Skipping line 6128: ',' expected after '"'
Skipping line 6147: ',' expected after '"'
Skipping line 6164: ',' expected after '"'
Skipping line 6201: ',' expected after '"'
Skipping line 6307: ',' expected after '"'
Skipping line 6323: ',' expected after '"'
Skipping line 6363: ',' expected after '"'
Skipping line 6423: ',' expected after '"'
Skipping line 6431: ',' expected after '"'
Skipping line 6439: ',' expected after '"'
Skipping line 6462: ',' expected after '"'
Skipping line 6463: ',' expected after '"'
Skipping line 6485: ',' expected after '"'
Skipping line 6497: ',' expected after '"'
Skipping line 6512: ',' expected after '"'
Skipping line 6533: ',' expected after '"'
Skipping line 6601: ',' expected after '"'
Skipping line 6668: ',' expected after '"'
Skipping line 6682: ',' expected after '"'
Skipping line 6825: ',' expected after '"'
Skipping line 6864: ',' expected after '"'
Skipping line 6897: ',' expected after '"'
Skipping line 6920: ',' expected after '"'
Skipping line 6926: ',' expected after '"'
Skipping line 6932: ',' expected after '"'
Skipping line 7034: ',' expected after '"'
Skipping line 7066: ',' expected after '"'
Skipping line 7106: ',' expected after '"'
Skipping line 7146: ',' expected after '"'
Skipping line 7197: ',' expected after '"'
Skipping line 7202: ',' expected after '"'
Skipping line 7297: ',' expected after '"'
Skipping line 7361: ',' expected after '"'
Skipping line 7386: ',' expected after '"'
Skipping line 7500: ',' expected after '"'
Skipping line 7730: ',' expected after '"'
Skipping line 7735: ',' expected after '"'
Skipping line 7758: ',' expected after '"'
Skipping line 7787: ',' expected after '"'
Skipping line 7794: ',' expected after '"'
Skipping line 7808: ',' expected after '"'
Skipping line 7839: ',' expected after '"'
Skipping line 7847: ',' expected after '"'
Skipping line 7868: ',' expected after '"'
Skipping line 7869: ',' expected after '"'
Skipping line 7936: ',' expected after '"'
Skipping line 7966: ',' expected after '"'
Skipping line 7974: ',' expected after '"'
Skipping line 8024: ',' expected after '"'
Skipping line 8028: ',' expected after '"'
Skipping line 8038: ',' expected after '"'
Skipping line 8062: ',' expected after '"'
Skipping line 8125: ',' expected after '"'
Skipping line 8139: ',' expected after '"'
Skipping line 8186: ',' expected after '"'
Skipping line 8194: ',' expected after '"'
Skipping line 8231: ',' expected after '"'
Skipping line 8233: ',' expected after '"'
Skipping line 8277: ',' expected after '"'
Skipping line 8343: ',' expected after '"'
Skipping line 8350: ',' expected after '"'
Skipping line 8354: ',' expected after '"'
Skipping line 8390: ',' expected after '"'
Skipping line 8404: ',' expected after '"'
Skipping line 8442: ',' expected after '"'
Skipping line 8447: ',' expected after '"'
Skipping line 8514: ',' expected after '"'
Skipping line 8559: ',' expected after '"'
Skipping line 8561: ',' expected after '"'
Skipping line 8593: ',' expected after '"'
Skipping line 8679: ',' expected after '"'
Skipping line 8687: ',' expected after '"'
Skipping line 8716: ',' expected after '"'
Skipping line 8717: ',' expected after '"'
Skipping line 8724: ',' expected after '"'
Skipping line 8731: ',' expected after '"'
Skipping line 8781: ',' expected after '"'
Skipping line 8797: ',' expected after '"'
Skipping line 8811: ',' expected after '"'
Skipping line 8823: ',' expected after '"'
Skipping line 8835: ',' expected after '"'
Skipping line 8907: ',' expected after '"'
Skipping line 8925: ',' expected after '"'
Skipping line 8960: ',' expected after '"'
Skipping line 8995: ',' expected after '"'
Skipping line 9037: ',' expected after '"'
Skipping line 9091: ',' expected after '"'
Skipping line 9105: ',' expected after '"'
Skipping line 9123: ',' expected after '"'
Skipping line 9157: ',' expected after '"'
Skipping line 9169: ',' expected after '"'
Skipping line 9220: ',' expected after '"'
Skipping line 9233: ',' expected after '"'
Skipping line 9266: ',' expected after '"'
Skipping line 9540: ',' expected after '"'
Skipping line 9545: ',' expected after '"'
Skipping line 9548: ',' expected after '"'
Skipping line 9569: ',' expected after '"'
Skipping line 9671: ',' expected after '"'
Skipping line 9688: ',' expected after '"'
Skipping line 9713: ',' expected after '"'
Skipping line 9723: ',' expected after '"'
Skipping line 9725: ',' expected after '"'
Skipping line 9732: ',' expected after '"'
Skipping line 9733: ',' expected after '"'
Skipping line 9752: ',' expected after '"'
Skipping line 9786: ',' expected after '"'
Skipping line 9818: ',' expected after '"'
Skipping line 9827: ',' expected after '"'
Skipping line 9919: ',' expected after '"'
Skipping line 9959: ',' expected after '"'
Skipping line 9973: ',' expected after '"'
Skipping line 9975: ',' expected after '"'
Skipping line 9993: ',' expected after '"'
Skipping line 10038: ',' expected after '"'
Skipping line 10080: ',' expected after '"'
Skipping line 10082: ',' expected after '"'
Skipping line 10083: ',' expected after '"'
Skipping line 10109: ',' expected after '"'
Skipping line 10127: ',' expected after '"'
Skipping line 10166: ',' expected after '"'
Skipping line 10214: ',' expected after '"'
Skipping line 10220: ',' expected after '"'
Skipping line 10232: ',' expected after '"'
Skipping line 10239: ',' expected after '"'
Skipping line 10383: ',' expected after '"'
Skipping line 10411: ',' expected after '"'
Skipping line 10422: ',' expected after '"'
Skipping line 10458: ',' expected after '"'
Skipping line 10528: ',' expected after '"'
Skipping line 10542: ',' expected after '"'
Skipping line 10556: ',' expected after '"'
Skipping line 10601: ',' expected after '"'
Skipping line 10661: ',' expected after '"'
Skipping line 10789: ',' expected after '"'
Skipping line 10812: ',' expected after '"'
Skipping line 10840: ',' expected after '"'
Skipping line 10865: ',' expected after '"'
Skipping line 10939: ',' expected after '"'
Skipping line 10984: ',' expected after '"'
Skipping line 11015: ',' expected after '"'
Skipping line 11049: ',' expected after '"'
Skipping line 11093: ',' expected after '"'
Skipping line 11146: ',' expected after '"'
Skipping line 11211: ',' expected after '"'
Skipping line 11220: ',' expected after '"'
Skipping line 11223: ',' expected after '"'
Skipping line 11315: ',' expected after '"'
Skipping line 11346: ',' expected after '"'
Skipping line 11388: ',' expected after '"'
Skipping line 11396: ',' expected after '"'
Skipping line 11457: ',' expected after '"'
Skipping line 11479: ',' expected after '"'
Skipping line 11489: ',' expected after '"'
Skipping line 11514: ',' expected after '"'
Skipping line 11543: ',' expected after '"'
Skipping line 11570: ',' expected after '"'
Skipping line 11583: ',' expected after '"'
Skipping line 11591: ',' expected after '"'
Skipping line 11638: ',' expected after '"'
Skipping line 11649: ',' expected after '"'
Skipping line 11700: ',' expected after '"'
Skipping line 11704: ',' expected after '"'
Skipping line 11710: ',' expected after '"'
Skipping line 11754: ',' expected after '"'
Skipping line 11780: ',' expected after '"'
Skipping line 11819: ',' expected after '"'
Skipping line 11823: ',' expected after '"'
Skipping line 11866: ',' expected after '"'
Skipping line 11910: ',' expected after '"'
Skipping line 11973: ',' expected after '"'
Skipping line 12012: ',' expected after '"'
Skipping line 12060: ',' expected after '"'
Skipping line 12085: ',' expected after '"'
Skipping line 12099: ',' expected after '"'
Skipping line 12103: ',' expected after '"'
Skipping line 12128: ',' expected after '"'
Skipping line 12153: ',' expected after '"'
Skipping line 12203: ',' expected after '"'
Skipping line 12271: ',' expected after '"'
Skipping line 12286: ',' expected after '"'
Skipping line 12295: ',' expected after '"'
Skipping line 12296: ',' expected after '"'
Skipping line 12306: ',' expected after '"'
Skipping line 12382: ',' expected after '"'
Skipping line 12391: ',' expected after '"'
Skipping line 12400: ',' expected after '"'
Skipping line 12420: ',' expected after '"'
Skipping line 12442: ',' expected after '"'
Skipping line 12444: ',' expected after '"'
Skipping line 12458: ',' expected after '"'
Skipping line 12496: ',' expected after '"'
Skipping line 12519: ',' expected after '"'
Skipping line 12539: ',' expected after '"'
Skipping line 12557: ',' expected after '"'
Skipping line 12584: ',' expected after '"'
Skipping line 12605: ',' expected after '"'
Skipping line 12628: ',' expected after '"'
Skipping line 12673: ',' expected after '"'
Skipping line 12693: ',' expected after '"'
Skipping line 12795: ',' expected after '"'
Skipping line 12799: ',' expected after '"'
Skipping line 12818: ',' expected after '"'
Skipping line 12835: ',' expected after '"'
Skipping line 12861: ',' expected after '"'
Skipping line 12864: ',' expected after '"'
Skipping line 12867: ',' expected after '"'
Skipping line 12894: ',' expected after '"'
Skipping line 12945: ',' expected after '"'
Skipping line 12952: ',' expected after '"'
Skipping line 12970: ',' expected after '"'
Skipping line 12972: ',' expected after '"'
Skipping line 12982: ',' expected after '"'
Skipping line 12984: ',' expected after '"'
Skipping line 13049: ',' expected after '"'
Skipping line 13119: ',' expected after '"'
Skipping line 13167: ',' expected after '"'
Skipping line 13232: ',' expected after '"'
Skipping line 13251: ',' expected after '"'
Skipping line 13259: ',' expected after '"'
Skipping line 13260: ',' expected after '"'
Skipping line 13310: ',' expected after '"'
Skipping line 13312: ',' expected after '"'
Skipping line 13314: ',' expected after '"'
Skipping line 13319: ',' expected after '"'
Skipping line 13326: ',' expected after '"'
Skipping line 13390: ',' expected after '"'
Skipping line 13431: ',' expected after '"'
Skipping line 13444: ',' expected after '"'
Skipping line 13502: ',' expected after '"'
Skipping line 13552: ',' expected after '"'
Skipping line 13558: ',' expected after '"'
Skipping line 13598: ',' expected after '"'
Skipping line 13602: ',' expected after '"'
Skipping line 13646: ',' expected after '"'
Skipping line 13717: ',' expected after '"'
Skipping line 13743: ',' expected after '"'
Skipping line 13759: ',' expected after '"'
Skipping line 13806: ',' expected after '"'
Skipping line 13894: ',' expected after '"'
Skipping line 13982: ',' expected after '"'
Skipping line 14084: ',' expected after '"'
Skipping line 14098: ',' expected after '"'
Skipping line 14156: ',' expected after '"'
Skipping line 14161: ',' expected after '"'
Skipping line 14251: ',' expected after '"'
Skipping line 14336: ',' expected after '"'
Skipping line 14360: ',' expected after '"'
Skipping line 14410: ',' expected after '"'
Skipping line 14425: ',' expected after '"'
Skipping line 14455: ',' expected after '"'
Skipping line 14470: ',' expected after '"'
Skipping line 14473: ',' expected after '"'
Skipping line 14497: ',' expected after '"'
Skipping line 14508: ',' expected after '"'
Skipping line 14556: ',' expected after '"'
Skipping line 14596: ',' expected after '"'
Skipping line 14680: ',' expected after '"'
Skipping line 14700: ',' expected after '"'
Skipping line 14705: ',' expected after '"'

In [ ]:
df.rename(columns = {'review':'text',	'sentiment': 'label'}, inplace = True)

In [ ]:
dfff = pd.read_csv("out.csv", error_bad_lines=False, engine="python")

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:3326: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version.


  exec(code_obj, self.user_global_ns, self.user_ns)

In [ ]:
dfff.rename(columns = {'Review':'text',	'Rating': 'label'}, inplace = True)

In [ ]:
dfff.loc[(dfff.label <=3 ), 'label'] = 'negative'
dfff.loc[(dfff.label == 4), 'label'] = 'neutral'
dfff.loc[(dfff.label == 5), 'label'] = 'positive'

In [ ]:
dfff

                                                     text     label
0       3D Touch просто восхитительная вещь! Заряд дер...  positive
1       Отключается при температуре близкой к нулю, не...   neutral
2       В Apple окончательно решили не заморачиваться,...  negative
3       Постарался наиболее ёмко и коротко описать все...   neutral
4       Достойный телефон. Пользоваться одно удовольст...  positive
...                                                   ...       ...
478913   часов разговоров, изредка пробки, инет очень ...  positive
478914  мой первый аппарат на андроиде. На данный моме...  positive
478915   часа wi-fi, 1 час разговоров, 1 час радио/мр3...  positive
478916  Разбил iphone и не было желания покупать новый...  positive
478917           Очень доволен покупкой и всем советую...  positive

[478918 rows x 2 columns]

In [ ]:
df_new.to_csv('phone.csv', index = True, index_label = 'id')

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
women = pd.read_csv('drive/MyDrive/csv/women.csv', lineterminator='\n')

In [ ]:
reviews = pd.read_csv('drive/MyDrive/csv/reviews.csv')

In [ ]:
reviews.rename(columns = {'label': 'text', 'text': 'label'}, inplace = True)

In [ ]:
reviews.to_csv('rewiews2.csv', index = False)

In [ ]:
reviews

            id                                               text  label
0            0  парфюм оригинальный . все ,  профессиональный ...      1
1            1  любимый dkny . запах просто шикарный . спасибо...      1
2            2  шикарный запах ! безумно нравиться ! не пожале...      1
3            3                                 иісі қатты ұнады .      1
4            4  запах просто классный ,  то ,  нужно летний вр...      0
...        ...                                                ...    ...
119043  119043  звук высокий средний ,  немного токсичный высо...      1
119044  119044  вполне сносный наушник ,  но ,  думать ,  не с...      0
119045  119045                               наушник просто супер      1
119046  119046                             все супер бас маловато      0
119047  119047  отличный звук . система шумоподавление . качес...      1

[119048 rows x 3 columns]

In [ ]:
women.label.unique()

array(['-1', nan,
       'negative  "2. Является ли товар таким же как на фотографии? ',
       ' все фотографии реальны. Мы сделали эти фотографии сами.  ',
       'neautral', '1',
       'positive  "Один размер   на мои параметры рост 168 и ОГ 80 сел отлично. Плечи с рукавами на месте. ',
       'positive  "It exceeded my expectations. Nice quality for the price. I am usually a smal'],
      dtype=object)

In [ ]:
women.dropna(inplace = True)

In [ ]:
women.reset_index()

       index     id                                               text label
0          0      0  качество плохое пошив ужасный (горловина напер...    -1
1          1      1  Товар отдали другому человеку,   я не получила...    -1
2          2      2  Ужасная синтетика! Тонкая, ничего общего с пре...    -1
3          3      3  товар не пришел,   продавец продлил защиту без...    -1
4          4      4    Кофточка голая синтетика,   носить не возможно.    -1
...      ...    ...                                                ...   ...
84755  89009  89009  сделано достаточно хорошо. на ткани сделан рис...     1
84756  89010  89010  Накидка шикарная. Спасибо большое провдо линяе...     1
84757  89011  89011  спасибо большое ) продовца рекомендую.. заказа...     1
84758  89012  89012  Очень довольна заказом! Меньше месяца в РБ.  К...     1
84759  89013  89013  хорошая куртка. постороннего запаха нет. швы р...     1

[84760 rows x 4 columns]

In [ ]:
women.label.unique()

array(['-1',
       'negative  "2. Является ли товар таким же как на фотографии? ',
       ' все фотографии реальны. Мы сделали эти фотографии сами.  ',
       'neautral', '1',
       'positive  "Один размер   на мои параметры рост 168 и ОГ 80 сел отлично. Плечи с рукавами на месте. ',
       'positive  "It exceeded my expectations. Nice quality for the price. I am usually a smal'],
      dtype=object)

In [ ]:
women[women.label == 'negative  "2. Является ли товар таким же как на фотографии? '].drop(index)

NameError: ignored

In [ ]:
women = women[women.label != 'positive  "It exceeded my expectations. Nice quality for the price. I am usually a smal']

In [ ]:
women.to_csv('women2.csv', index = False)

In [ ]:
women.label.unique()

array(['-1', 0, '1'], dtype=object)

In [ ]:
women.label = pd.to_numeric(women.label)

In [ ]:
women.label.unique()

array([-1,  0,  1])

In [ ]:
women

          id                                               text  label
0          0  качество плохое пошив ужасный (горловина напер...     -1
1          1  Товар отдали другому человеку,   я не получила...     -1
2          2  Ужасная синтетика! Тонкая, ничего общего с пре...     -1
3          3  товар не пришел,   продавец продлил защиту без...     -1
4          4    Кофточка голая синтетика,   носить не возможно.     -1
...      ...                                                ...    ...
89009  89009  сделано достаточно хорошо. на ткани сделан рис...      1
89010  89010  Накидка шикарная. Спасибо большое провдо линяе...      1
89011  89011  спасибо большое ) продовца рекомендую.. заказа...      1
89012  89012  Очень довольна заказом! Меньше месяца в РБ.  К...      1
89013  89013  хорошая куртка. постороннего запаха нет. швы р...      1

[84756 rows x 3 columns]

In [ ]:
women.loc[(women.label == 'neautral'), 'label'] = 0

In [ ]:
women.label.unique()

array(['-1',
       'negative  "2. Является ли товар таким же как на фотографии? ',
       ' все фотографии реальны. Мы сделали эти фотографии сами.  ', 0,
       '1',
       'positive  "Один размер   на мои параметры рост 168 и ОГ 80 сел отлично. Плечи с рукавами на месте. ',
       'positive  "It exceeded my expectations. Nice quality for the price. I am usually a smal'],
      dtype=object)

In [ ]:
women.drop()

ValueError: ignored

In [ ]:
women.label.isna().sum()

0

In [ ]:
phone.label.isna().count()

478918

In [ ]:
phone.label.unique()

array([ 1,  0, -1])